# Generated by Django 6.0.3 on 2026-04-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID (Paymenku)')),
                ('reference_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Nominal Tagihan')),
                ('payment_channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metode Pembayaran')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Berhasil'), ('expired', 'Kedaluwarsa'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('pay_url', models.URLField(blank=True, null=True, verbose_name='URL Pembayaran')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Terbayar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Data Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
    ]
