# Generated by Django 6.0.3 on 2026-04-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Pembayaran'),
        ),
    ]
