# Generated by Django 6.0.3 on 2026-04-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Menu')),
                ('price', models.PositiveIntegerField(verbose_name='Harga')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Gambar')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Data Menu',
                'ordering': ['-is_available', 'name'],
            },
        ),
    ]
