# Generated by Django 6.0.3 on 2026-04-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Menu')),
                ('price', models.PositiveIntegerField(verbose_name='Harga')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Gambar')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Data Menu',
                'ordering': ['-is_available', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menus/%Y/%m/', verbose_name='Gambar Menu')),
                ('alt_text', models.CharField(blank=True, default='', max_length=120, verbose_name='Alt Text')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menus.menu')),
            ],
            options={
                'verbose_name': 'Gambar Menu',
                'verbose_name_plural': 'Gambar Menu',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
