# Generated by Django 6.0.3 on 2026-04-03 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=50, unique=True, verbose_name='ID Referensi')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('table_number', models.PositiveIntegerField(verbose_name='Nomor Meja')),
                ('status', models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('cooking', 'Sedang Diproses'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan'), ('expired', 'Kedaluwarsa')], default='pending_payment', max_length=20)),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Total Harga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Data Pesanan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('price', models.PositiveIntegerField(verbose_name='Harga Satuan (Snapshot)')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Item Pesanan',
                'verbose_name_plural': 'Detail Item Pesanan',
            },
        ),
    ]
